# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" "wl" "applesmc"];
  boot.extraModulePackages = [ "${config.boot.kernelPackages.broadcom_sta}" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/eaa9fb02-f452-4a8e-9371-8434a8bc67ea";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/67E3-17ED";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d600af45-e7b1-430a-b7a4-2391f715dbd7"; }
    ];

  nix.maxJobs = 8;
}
